-- Game instructions: auto-generated by Gemma, describes how to play each game
CREATE TABLE IF NOT EXISTS autonomous_arcade_game_instructions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id     UUID REFERENCES autonomous_arcade_games(id) ON DELETE CASCADE,
  slug        TEXT NOT NULL,
  instructions TEXT NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS aa_game_instructions_slug ON autonomous_arcade_game_instructions(slug);

-- Chat messages: stored for analytics/training, not used for context (stateless API)
CREATE TABLE IF NOT EXISTS autonomous_arcade_chat_messages (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  TEXT NOT NULL,
  game_slug   TEXT,
  role        TEXT NOT NULL CHECK (role IN ('player', 'ai')),
  content     TEXT NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS aa_chat_session_idx ON autonomous_arcade_chat_messages(session_id);
CREATE INDEX IF NOT EXISTS aa_chat_game_idx ON autonomous_arcade_chat_messages(game_slug);
